# Generated by Django 5.0.6 on 2024-06-02 22:19

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('email', models.CharField(max_length=320, validators=[django.core.validators.EmailValidator()])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, unique=True)),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='base.local')),
                ('origem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='base.local')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.SmallIntegerField()),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
                ('trajeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trajeto')),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField()),
                ('assentos_disponveis', models.IntegerField(default=1)),
                ('em_aberto', models.BooleanField(default=True)),
                ('retorno', models.BooleanField(default=False)),
                ('apenas_solicitacao', models.BooleanField(default=False)),
                ('detalhes_adicionais', models.TextField(max_length=512)),
                ('motorista_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.motorista')),
                ('trajeto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trajeto')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carona')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.usuario'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('cor', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('ano', models.IntegerField()),
                ('marca', models.CharField(max_length=256)),
                ('motorista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.motorista')),
            ],
        ),
    ]
