# Generated by Django 5.0.6 on 2024-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parada',
            old_name='local_id',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='parada',
            old_name='trajeto_id',
            new_name='trajeto',
        ),
        migrations.RenameField(
            model_name='passageiro',
            old_name='carona_id',
            new_name='carona',
        ),
        migrations.RenameField(
            model_name='passageiro',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='trajeto',
            old_name='destino_id',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='trajeto',
            old_name='origem_id',
            new_name='origem',
        ),
    ]
