# Generated by Django 5.0.6 on 2024-06-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usuario_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
            ],
        ),
        migrations.CreateModel(
            name='LocalPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, unique=True)),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.BigIntegerField(unique=True)),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField()),
                ('assentos_disponveis', models.IntegerField(default=1)),
                ('em_aberto', models.BooleanField(default=True)),
                ('retorno', models.BooleanField(default=False)),
                ('apenas_solicitacao', models.BooleanField(default=False)),
                ('detalhes_adicionais', models.TextField(max_length=512)),
                ('motorista_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carona')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='base.local')),
                ('origem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='base.local')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.SmallIntegerField()),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
                ('trajeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trajeto')),
            ],
        ),
        migrations.AddField(
            model_name='carona',
            name='trajeto_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trajeto'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('cor', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('ano', models.IntegerField()),
                ('marca', models.CharField(max_length=256)),
                ('motorista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.motorista')),
            ],
        ),
    ]
