# Generated by Django 5.0.6 on 2024-06-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_local_id_parada_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='trajeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='base.trajeto'),
        ),
    ]
