# Generated by Django 5.0.6 on 2024-06-17 15:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_parada_trajeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCarona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField(default=datetime.date.today)),
                ('quantidade_passageiros', models.IntegerField(default=1)),
                ('em_aberto', models.BooleanField(default=1)),
                ('passa_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trajeto')),
            ],
        ),
    ]
